[package]
name = "discord_v5_bot"
version = "0.1.0"
authors = ["Ben Wilson ben.aiken.wilson@gmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
